# Generated by Django 4.1.13 on 2024-05-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_author_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Status",
            field=models.CharField(
                choices=[("DT", "Draft"), ("PB", "Published")],
                default="DT",
                max_length=2,
            ),
        ),
    ]
